# Build
FROM node:10.16-alpine

# Create App Directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install Dependencies
COPY package*.json ./
COPY ./yarn.lock ./

# Installation de yarn en silence
RUN yarn install --silent

# Copy app source code
COPY . .

# Exports
EXPOSE 2000

#Démarre la commande
CMD ["yarn","start"]